<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;netstandard2.1;net6.0;net9.0</TargetFrameworks>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <InvariantGlobalization>true</InvariantGlobalization>
        <PackageId>Vencaa.FFmpeg.AutoGen.Wrapper</PackageId>
        <Description>Mostly safe FFmpeg API wrapper based on FFmpeg.AutoGen.</Description>
        <Version>7.1.1.0-dev</Version>
        <Product>Vencaa.FFmpeg.AutoGen.Wrapper</Product>
        <PackageProjectUrl>https://github.com/VendaGamer/FFmpegWrapper</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Authors>VendaGamer</Authors>
        <PackageOutputPath>$(SolutionDir)artifacts</PackageOutputPath>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
        <EnableAotAnalyzer>true</EnableAotAnalyzer>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>CS1591;CS1573</NoWarn>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="CommunityToolkit.HighPerformance" PrivateAssets="All"/>
        <PackageReference Include="Microsoft.NETCore.Platforms" />
        <PackageReference Include="OwnerCore" />
        <PackageReference Include="System.Collections.Immutable" />
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" />

    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\FFmpegWrapper.Abstractions\FFmpegWrapper.Abstractions.csproj" />
    </ItemGroup>
</Project>