<Project>
    
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <InvariantGlobalization>true</InvariantGlobalization>
        <IsPackable>false</IsPackable>
        <BaseOutputPath>../build</BaseOutputPath>
        <UseCurrentRuntimeIdentifier>true</UseCurrentRuntimeIdentifier>
        <RuntimeIdentifiers>any</RuntimeIdentifiers>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../Deps/Bindings/FFmpegBindings.Linked/FFmpegBindings.Linked.csproj" />
        <ProjectReference Include="../../FFmpegWrapper/FFmpegWrapper.csproj" />
    </ItemGroup>
    
</Project>